default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pictweet_development

test:
  <<: *default
  database: pictweet_test

production:
  <<: *default
  database: pictweet_production
  username: pictweet
  password: <%= ENV["PICTWEET_DATABASE_PASSWORD"] %>
